INDIGO_WELCOME_MESSAGE: "HỆ THỐNG ĐÀO TẠO LẬP TRÌNH HIỆN ĐẠI"
INDIGO_PRIMARY_COLOR: "#272882"

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "/tos"
    - title: "CodeGym theme for Open edX"
      url: "https://github.com/hoadh/codegym-edx-theme"
